import { Store, Product } from './types';

export const stores: Store[] = [
  {
    id: '1',
    name: 'AL RABEE SUPERMARKET - Muscat',
    address: 'Al Khuwair, Muscat, Oman',
    phone: '+968 2456 7890',
    hours: '7:00 AM - 11:00 PM',
    lat: 23.5880,
    lng: 58.3829,
  },
  {
    id: '2',
    name: 'AL RABEE SUPERMARKET - Salalah',
    address: 'Al Saada, Salalah, Oman',
    phone: '+968 2327 8901',
    hours: '7:00 AM - 12:00 AM',
    lat: 17.0151,
    lng: 54.0924,
  },
];

export const products: Product[] = [
  // ── Fruits ──
  {
    id: '1',
    name: 'Organic Bananas',
    description: 'Fresh organic bananas, imported',
    price: 0.450,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400',
    discount: 15,
    isTopSelling: true,
    isFeatured: true,
    location: { aisle: 'A1', section: 'Produce' },
    inventory: { store: 150, warehouse: 500 },
  },
  {
    id: '5',
    name: 'Fresh Strawberries',
    description: 'Sweet and juicy strawberries, 250g pack',
    price: 1.200,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=400',
    discount: 10,
    isTopSelling: false,
    isFeatured: true,
    location: { aisle: 'A1', section: 'Produce' },
    inventory: { store: 35, warehouse: 120 },
  },
  {
    id: '13',
    name: 'Red Apples',
    description: 'Crispy red apples, per kg',
    price: 0.800,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=400',
    isTopSelling: true,
    isFeatured: false,
    location: { aisle: 'A1', section: 'Produce' },
    inventory: { store: 200, warehouse: 600 },
  },
  {
    id: '14',
    name: 'Fresh Mangoes',
    description: 'Alphonso mangoes, sweet and ripe',
    price: 1.500,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1553279768-865429fa0078?w=400',
    discount: 20,
    isTopSelling: true,
    isFeatured: true,
    location: { aisle: 'A1', section: 'Produce' },
    inventory: { store: 80, warehouse: 300 },
  },
  {
    id: '15',
    name: 'Fresh Oranges',
    description: 'Juicy navel oranges, per kg',
    price: 0.600,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1547514701-42782101795e?w=400',
    isTopSelling: false,
    isFeatured: false,
    location: { aisle: 'A1', section: 'Produce' },
    inventory: { store: 180, warehouse: 500 },
  },
  {
    id: '16',
    name: 'Watermelon',
    description: 'Whole seedless watermelon, ~5 kg',
    price: 1.800,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1589984662646-e7b2e4962f18?w=400',
    isTopSelling: false,
    isFeatured: false,
    location: { aisle: 'A2', section: 'Produce' },
    inventory: { store: 40, warehouse: 100 },
  },

  // ── Vegetables ──
  {
    id: '9',
    name: 'Fresh Tomatoes',
    description: 'Vine-ripened tomatoes, per kg',
    price: 0.350,
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1546094096-0df4bcaaa337?w=400',
    isTopSelling: true,
    isFeatured: false,
    location: { aisle: 'A2', section: 'Produce' },
    inventory: { store: 100, warehouse: 400 },
  },
  {
    id: '17',
    name: 'Cucumbers',
    description: 'Fresh green cucumbers, per kg',
    price: 0.250,
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?w=400',
    isTopSelling: true,
    isFeatured: false,
    location: { aisle: 'A2', section: 'Produce' },
    inventory: { store: 120, warehouse: 350 },
  },
  {
    id: '18',
    name: 'Fresh Potatoes',
    description: 'Locally sourced potatoes, per kg',
    price: 0.300,
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1518977676601-b53f82abe647?w=400',
    isTopSelling: true,
    isFeatured: false,
    location: { aisle: 'A2', section: 'Produce' },
    inventory: { store: 200, warehouse: 700 },
  },
  {
    id: '19',
    name: 'Onions',
    description: 'Yellow onions, per kg',
    price: 0.200,
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=400',
    isTopSelling: false,
    isFeatured: false,
    location: { aisle: 'A2', section: 'Produce' },
    inventory: { store: 250, warehouse: 800 },
  },
  {
    id: '20',
    name: 'Bell Peppers',
    description: 'Mixed colour bell peppers, pack of 3',
    price: 0.750,
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=400',
    discount: 10,
    isTopSelling: false,
    isFeatured: true,
    location: { aisle: 'A2', section: 'Produce' },
    inventory: { store: 60, warehouse: 200 },
  },

  // ── Dairy ──
  {
    id: '2',
    name: 'Fresh Milk 1 Litre',
    description: 'Full cream fresh milk, pasteurised',
    price: 0.550,
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400',
    isTopSelling: true,
    isFeatured: false,
    location: { aisle: 'B3', section: 'Refrigerated' },
    inventory: { store: 80, warehouse: 300 },
  },
  {
    id: '6',
    name: 'Greek Yogurt',
    description: 'Plain Greek yogurt, 500g',
    price: 0.950,
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400',
    isTopSelling: false,
    isFeatured: false,
    location: { aisle: 'B3', section: 'Refrigerated' },
    inventory: { store: 55, warehouse: 180 },
  },
  {
    id: '8',
    name: 'Farm Fresh Eggs',
    description: 'Free-range eggs, tray of 30',
    price: 1.800,
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=400',
    isTopSelling: true,
    isFeatured: true,
    location: { aisle: 'B2', section: 'Refrigerated' },
    inventory: { store: 90, warehouse: 300 },
  },
  {
    id: '12',
    name: 'Cheddar Cheese',
    description: 'Sharp cheddar cheese block, 200g',
    price: 1.250,
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=400',
    discount: 10,
    isTopSelling: true,
    isFeatured: false,
    location: { aisle: 'B3', section: 'Refrigerated' },
    inventory: { store: 65, warehouse: 200 },
  },
  {
    id: '21',
    name: 'Laban (Buttermilk)',
    description: 'Chilled traditional laban, 1 litre',
    price: 0.400,
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400',
    isTopSelling: true,
    isFeatured: false,
    location: { aisle: 'B3', section: 'Refrigerated' },
    inventory: { store: 100, warehouse: 350 },
  },

  // ── Meat ──
  {
    id: '3',
    name: 'Fresh Chicken Breast',
    description: 'Boneless skinless chicken breast, 1 kg',
    price: 2.500,
    category: 'Meat',
    image: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=400',
    discount: 20,
    isTopSelling: true,
    isFeatured: true,
    location: { aisle: 'C2', section: 'Meat Counter' },
    inventory: { store: 45, warehouse: 200 },
  },
  {
    id: '7',
    name: 'Minced Beef',
    description: 'Fresh ground beef, 500g pack',
    price: 2.200,
    category: 'Meat',
    image: 'https://images.unsplash.com/photo-1603048588665-791ca8aea617?w=400',
    discount: 15,
    isTopSelling: true,
    isFeatured: false,
    location: { aisle: 'C2', section: 'Meat Counter' },
    inventory: { store: 70, warehouse: 250 },
  },
  {
    id: '22',
    name: 'Whole Chicken',
    description: 'Fresh whole chicken, ~1.2 kg',
    price: 1.800,
    category: 'Meat',
    image: 'https://images.unsplash.com/photo-1587593810167-a84920ea0781?w=400',
    isTopSelling: true,
    isFeatured: false,
    location: { aisle: 'C1', section: 'Meat Counter' },
    inventory: { store: 50, warehouse: 180 },
  },
  {
    id: '23',
    name: 'Lamb Leg',
    description: 'Fresh lamb leg, bone-in, per kg',
    price: 4.500,
    category: 'Meat',
    image: 'https://images.unsplash.com/photo-1602470520998-f4a52199a3d6?w=400',
    isTopSelling: false,
    isFeatured: false,
    location: { aisle: 'C2', section: 'Meat Counter' },
    inventory: { store: 30, warehouse: 100 },
  },

  // ── Bakery ──
  {
    id: '4',
    name: 'Whole Wheat Bread',
    description: 'Freshly baked whole wheat bread loaf',
    price: 0.350,
    category: 'Bakery',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400',
    isTopSelling: true,
    isFeatured: false,
    location: { aisle: 'D1', section: 'Bakery' },
    inventory: { store: 60, warehouse: 150 },
  },
  {
    id: '24',
    name: 'Arabic Flatbread',
    description: 'Pack of 5 traditional Arabic flatbreads',
    price: 0.300,
    category: 'Bakery',
    image: 'https://images.unsplash.com/photo-1586444248902-2f64eddc13df?w=400',
    isTopSelling: true,
    isFeatured: true,
    location: { aisle: 'D1', section: 'Bakery' },
    inventory: { store: 100, warehouse: 400 },
  },
  {
    id: '25',
    name: 'Croissants',
    description: 'Butter croissants, pack of 4',
    price: 0.800,
    category: 'Bakery',
    image: 'https://images.unsplash.com/photo-1549903072-7e6e0bedb7bc?w=400',
    discount: 15,
    isTopSelling: false,
    isFeatured: false,
    location: { aisle: 'D1', section: 'Bakery' },
    inventory: { store: 40, warehouse: 120 },
  },

  // ── Beverages ──
  {
    id: '11',
    name: 'Orange Juice',
    description: 'Fresh squeezed orange juice, 1 litre',
    price: 0.850,
    category: 'Beverages',
    image: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400',
    isTopSelling: false,
    isFeatured: false,
    location: { aisle: 'B4', section: 'Refrigerated' },
    inventory: { store: 40, warehouse: 150 },
  },
  {
    id: '26',
    name: 'Mineral Water (6-pack)',
    description: '1.5L bottles, pack of 6',
    price: 0.750,
    category: 'Beverages',
    image: 'https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=400',
    isTopSelling: true,
    isFeatured: false,
    location: { aisle: 'E1', section: 'Beverages' },
    inventory: { store: 200, warehouse: 800 },
  },
  {
    id: '27',
    name: 'Arabic Coffee (Qahwa)',
    description: 'Traditional ground Arabic coffee, 250g',
    price: 2.500,
    category: 'Beverages',
    image: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400',
    isTopSelling: true,
    isFeatured: true,
    location: { aisle: 'E2', section: 'Beverages' },
    inventory: { store: 60, warehouse: 200 },
  },
  {
    id: '28',
    name: 'Green Tea',
    description: 'Premium green tea bags, box of 25',
    price: 0.950,
    category: 'Beverages',
    image: 'https://images.unsplash.com/photo-1556881286-fc6915169721?w=400',
    isTopSelling: false,
    isFeatured: false,
    location: { aisle: 'E2', section: 'Beverages' },
    inventory: { store: 80, warehouse: 250 },
  },

  // ── Pantry / Dry Goods ──
  {
    id: '10',
    name: 'Basmati Rice 5kg',
    description: 'Premium long grain basmati rice',
    price: 3.500,
    category: 'Pantry',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400',
    discount: 10,
    isTopSelling: true,
    isFeatured: true,
    location: { aisle: 'E4', section: 'Dry Goods' },
    inventory: { store: 120, warehouse: 500 },
  },
  {
    id: '29',
    name: 'Spaghetti Pasta',
    description: 'Italian spaghetti, 500g pack',
    price: 0.450,
    category: 'Pantry',
    image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400',
    isTopSelling: false,
    isFeatured: false,
    location: { aisle: 'E4', section: 'Dry Goods' },
    inventory: { store: 150, warehouse: 500 },
  },
  {
    id: '30',
    name: 'Cooking Oil 1.5L',
    description: 'Vegetable cooking oil, 1.5 litre bottle',
    price: 1.200,
    category: 'Pantry',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400',
    isTopSelling: true,
    isFeatured: false,
    location: { aisle: 'E3', section: 'Dry Goods' },
    inventory: { store: 90, warehouse: 400 },
  },
  {
    id: '31',
    name: 'White Sugar 1kg',
    description: 'Fine white sugar, 1 kg bag',
    price: 0.350,
    category: 'Pantry',
    image: 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=400',
    isTopSelling: true,
    isFeatured: false,
    location: { aisle: 'E3', section: 'Dry Goods' },
    inventory: { store: 180, warehouse: 600 },
  },
  {
    id: '32',
    name: 'All-Purpose Flour 2kg',
    description: 'Premium all-purpose wheat flour',
    price: 0.650,
    category: 'Pantry',
    image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400',
    isTopSelling: false,
    isFeatured: false,
    location: { aisle: 'E3', section: 'Dry Goods' },
    inventory: { store: 100, warehouse: 350 },
  },
  {
    id: '33',
    name: 'Canned Chickpeas',
    description: 'Ready-to-eat chickpeas, 400g tin',
    price: 0.350,
    category: 'Pantry',
    image: 'https://images.unsplash.com/photo-1607532941433-304659e8198a?w=400',
    isTopSelling: false,
    isFeatured: false,
    location: { aisle: 'E5', section: 'Canned Goods' },
    inventory: { store: 120, warehouse: 400 },
  },
  {
    id: '34',
    name: 'Tomato Paste',
    description: 'Concentrated tomato paste, 200g tin',
    price: 0.250,
    category: 'Pantry',
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=400',
    isTopSelling: false,
    isFeatured: false,
    location: { aisle: 'E5', section: 'Canned Goods' },
    inventory: { store: 150, warehouse: 500 },
  },

  // ── Snacks ──
  {
    id: '35',
    name: 'Mixed Nuts',
    description: 'Roasted mixed nuts, 250g pack',
    price: 1.500,
    category: 'Snacks',
    image: 'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=400',
    discount: 15,
    isTopSelling: true,
    isFeatured: true,
    location: { aisle: 'F1', section: 'Snacks' },
    inventory: { store: 70, warehouse: 250 },
  },
  {
    id: '36',
    name: 'Potato Chips',
    description: 'Salted potato chips, 160g',
    price: 0.500,
    category: 'Snacks',
    image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=400',
    isTopSelling: true,
    isFeatured: false,
    location: { aisle: 'F1', section: 'Snacks' },
    inventory: { store: 150, warehouse: 500 },
  },
  {
    id: '37',
    name: 'Dates (Kholas)',
    description: 'Premium Omani Kholas dates, 500g',
    price: 2.000,
    category: 'Snacks',
    image: 'https://images.unsplash.com/photo-1590779033100-9f60a05a013d?w=400',
    isTopSelling: true,
    isFeatured: true,
    location: { aisle: 'F2', section: 'Snacks' },
    inventory: { store: 80, warehouse: 300 },
  },
  {
    id: '38',
    name: 'Chocolate Bar',
    description: 'Milk chocolate bar, 100g',
    price: 0.650,
    category: 'Snacks',
    image: 'https://images.unsplash.com/photo-1575377427642-087cf684f29d?w=400',
    isTopSelling: false,
    isFeatured: false,
    location: { aisle: 'F1', section: 'Snacks' },
    inventory: { store: 100, warehouse: 350 },
  },

  // ── Household ──
  {
    id: '39',
    name: 'Dish Soap',
    description: 'Liquid dish soap, lemon scent, 750ml',
    price: 0.650,
    category: 'Household',
    image: 'https://images.unsplash.com/photo-1622467827417-bbe2237067a9?w=400',
    isTopSelling: false,
    isFeatured: false,
    location: { aisle: 'G1', section: 'Cleaning' },
    inventory: { store: 80, warehouse: 300 },
  },
  {
    id: '40',
    name: 'Tissue Box (5-pack)',
    description: 'Soft facial tissues, 5 boxes',
    price: 1.100,
    category: 'Household',
    image: 'https://images.unsplash.com/photo-1584556812952-905ffd0c611a?w=400',
    isTopSelling: true,
    isFeatured: false,
    location: { aisle: 'G2', section: 'Paper Products' },
    inventory: { store: 100, warehouse: 400 },
  },
  {
    id: '41',
    name: 'Laundry Detergent 3kg',
    description: 'Automatic washing powder, 3 kg',
    price: 2.800,
    category: 'Household',
    image: 'https://images.unsplash.com/photo-1582735689369-4fe89db7114c?w=400',
    discount: 20,
    isTopSelling: true,
    isFeatured: false,
    location: { aisle: 'G1', section: 'Cleaning' },
    inventory: { store: 50, warehouse: 200 },
  },
];

export const categories = [
  'All',
  'Fruits',
  'Vegetables',
  'Dairy',
  'Meat',
  'Bakery',
  'Beverages',
  'Pantry',
  'Snacks',
  'Household',
];
